// Generated from docs/openapi.yaml by `npm run generate:openapi-types`.
// Do not edit this file by hand.

export interface OpenApiPaths {
  '/auth/login': {
    post: { response: unknown };
  };
  '/auth/refresh': {
    post: { response: unknown };
  };
  '/admin/auth/login': {
    post: { response: unknown };
  };
  '/admin/users': {
    get: { response: import('./admin').AdminUsersPage };
  };
  '/admin/amas/config': {
    get: { response: import('./amas').AmasConfig };
    put: { response: { updated: boolean; versionHash?: string; versionId?: number } };
  };
  '/admin/amas/metrics/timeseries': {
    get: { response: import('../api/admin').AmasMetricsTimeseriesPoint[] };
  };
  '/admin/updates/status': {
    get: { response: import('./admin').AdminUpdateStatus };
  };
}

export type OpenApiPath = keyof OpenApiPaths;
